### PR TITLE
Update yarn.lock as a result of running yarn install

### PR DESCRIPTION
**Pull request by acelaya**
Fixing some inconsistencies in the lockfile due to common shared dependencies from different dependabot PRs

### CODE REVIEW

**Comment by robertknight** [comment]
I assume the changes in this PR were created by running `yarn install`? When creating a PR that is the result of some command, it is useful to mention that - eg. "This is the result of running `{command}` {details of any other changes that were made}".

**Review by lyzadanger — COMMENTED** [review]
Hi, @acelaya !

Would you mind updating the commit message per @robertknight 's suggestion? Thanks!

**Comment by acelaya** [comment]
> Hi, @acelaya !
> 
> Would you mind updating the commit message per @robertknight 's suggestion? Thanks!

Done

**Review by lyzadanger — APPROVED** [review]
👍🏻

**Pull request merged**
