### PR TITLE
Use placehold.co to generate placeholder images

### PR DESCRIPTION
**Pull request by acelaya**
We were using `placekitten.com` to generate placeholder images, but the service is no longer available.

This PR replaces that service with https://placehold.co, which generates a bit more boring images, but should work as a valid replacement.

### CODE REVIEW

**Review by robertknight — APPROVED** [review]
This is better than dead URLs, although it would be nice to have placeholders that allow you to see if the border gets cropped easily.

**Comment by acelaya** [comment]
> This is better than dead URLs, although it would be nice to have placeholders that allow you to see if the border gets cropped easily.

Yep, that was my thinking, but I couldn't find a service returning "actual" images. Most follow this pattern of returning an image with the size in the middle.

I found one returning random images from flickr. I thought that was a no go 😅

**Comment by robertknight** [comment]
> Yep, that was my thinking, but I couldn't find a service returning "actual" images. Most follow this pattern of returning an image with the size in the middle.

I discovered https://picsum.photos in my travels.

**Comment by acelaya** [comment]
There's one thing we could do though. We always use the 400x400 size, except in one test where we use the 300x300 one.

I have the suspicion the test one is not important, and for the others, we could just have a locally-stored image. There's no need for an external service to always use the same image.

**Comment by acelaya** [comment]
> > Yep, that was my thinking, but I couldn't find a service returning "actual" images. Most follow this pattern of returning an image with the size in the middle.
> 
> I discovered https://picsum.photos in my travels.

Hah! This one is nice

**Pull request merged**
